apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-elasticsearch-0
  namespace: kube-logging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
