apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
