apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sample-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: jenkins  '
  updatePolicy:
    updateMode: "Auto"  # Options: "Off", "Initial", "Auto"
