apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: jenkins    # must match Deployment pod label
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 
  type: LoadBalancer
